### ISSUE TITLE
Colour ramps

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#142]
Mike Brondjberg comments for us to discuss:

'The way the data is displayed as a continuous ramp in “Number of Storeys” works well… darker = lower, brighter = taller.
The “building age” colour scale is less intuitive and takes a few cognitive steps to understand what is old and what is new.
I see that age is being roughly grouped in “century” and then brightness ramped within a century.
This logic is not applied consistently as 1800 – 1900 is not running dark to light: 

cid:image004.png@01D47693.3FB40720

I would suggest, that what is more interesting to show, is the age as a continuous colour ramp (like building height).

Then perhaps show “century” in other ways…
An option in the UI to bucket the continuous colour ramp above into centuries
Or (maybe less good) an option to group buildings into distinct categorical colours.
An option in the ui to toggle on / off centuries (for users interested in specific centuries)
A rollver / tap popup on the map would help making the data more accessible, by not relying on colour perception understand specific buildings.
Likewise an interaction between the legend and the map… when you click / rollover the legend on the left, perhaps the buildings in that range are highlighted on the map?

**Comment by tomalrussell** [comment]
Also relevant for #183

**Comment by tomalrussell** [comment]
Age colour maps have been revised in 4c7edee2711aaa232886ae347df6be607f9dc5cf, may be updated again.
