### ISSUE TITLE
Add extra box for 'Decade in which built'  on age category

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#151]
Hi Tom, Sharon Richardson at CASA just made a very interesting suggestion - having tried out the age category, which I think it would be good to add in.  That is having under the 'Construction date' box another box which is ' Decade in which built', with a dropdown says 2000s, 1990s etc.  We'd keep everything else exactly as it is but this extra box would help make it less intimidating as a catagory so we'd probably get more uploads and , people could still add exact date if they know it

**Comment by tomalrussell** [comment]
- century
- decade
