### ISSUE TITLE
Address copyright within Historic England LBS (Listed Buildings) data and borough LBS

### ISSUE THREAD

**Issue by urbandataanalysts** [colouring-london/colouring-london#167]
Confirm if this is open and can be used to populate our address fields for LBS

**Comment by urbandataanalysts** [comment]
@tomalrussell I want to assign this to me but I don't have that option

**Comment by tomalrussell** [comment]
Just checking - 'HE LBS' == Historic England Listed Buildings?

**Comment by urbandataanalysts** [comment]
@tomalrussell Yes, apologies.
