### ISSUE TITLE
Missing buildings in conservation areas

### ISSUE THREAD

**Issue by dominijk** [colouring-london/colouring-london#193]
Hi @tomalrussell can i review this with you;

Below are two screengrabs one from the beta one from my local db copy on QGIS. There are a couple of buildings missing from the crescent on beta, these are within the conservation area but when I look at `building_properties.uprn_geom` there's not a point that falls within `geometries`. This might relate to #171 or I should i have made the join on `geometries` not `uprn_geom`? In which case I will re-run

![screen shot 2019-02-16 at 17 18 05](https://user-images.githubusercontent.com/6041913/52902882-03227980-320f-11e9-849f-258cff3612ee.png)
![screen shot 2019-02-16 at 17 17 48](https://user-images.githubusercontent.com/6041913/52902883-03227980-320f-11e9-827f-605b54b97b83.png)

**Comment by tomalrussell** [comment]
Thanks for looking into this @dominijk 

Yes, I think this is the issue described in #171 

Running the intersection (conservation area boundary <> geometries) as you suggest should catch all the building geometries :+1: 

(the UPRNs<>buildings join is not perfect, and uprn_geom is really in there for reference, not otherwise used in the site/app)

**Comment by dominijk** [comment]
@polly64 This relates to saturdays email thread. Will pick up and re run

**Comment by urbandataanalysts** [comment]
@tomalrussell I've sent an email with the updated data file

**Comment by tomalrussell** [comment]
@dominijk is this issue still live? Is it something you can run as a bulk upload?

**Comment by dominijk** [comment]
@tomalrussell Yes, it's ready to upload. Can I re-run the python script you made for the last time on the file, column headers etc should be the same

**Comment by tomalrussell** [comment]
[`load_conservation_areas.py`](https://github.com/tomalrussell/colouring-london/blob/master/etl/join_building_data/load_conservation_areas.py) should be good :+1:

Assumes CSV has columns `building_id` and `conservation_area_name`

Usage something like:
```
python load_conservation_areas.py <URL> <api-key> <path-to-data.csv>
python load_conservation_areas.py beta.colouring.london abcd1234cdef3456 ./conservation_areas.csv
```

You can test on an extract, or against a local install (pass `localhost:3000` as the URL). There should no harm in re-running, the site will happily make no changes if nothing changed.

You'll need [`requests`](https://2.python-requests.org/en/master/) and [`tqdm`](https://tqdm.github.io/). Install by running `pip install requests tqdm`
