### ISSUE TITLE
For Age category - add 4 extra subcategories

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#208]
1. To pick up major extensions/alterations we need to add a ' Dates of major extension/alterations' subcategory.  This will need a dropdown with numbers spanning 2019 back to 1000 so you can pick an ' estimated start date'- you need to be able to add at least 5 major extensions which can be explained  in the hint though this will apply to very few buildings.  Dom re listed buildings do u agree 5 possible extension periods is enough for early ones?

2. The second is a place to collect the  'date of any major energy retrofit' (or suggest other short wording).  This subcat also needs to  be reproduced in the 'Sustainability ' section - so that people can add either from 'Age' or 'Sustainability' and each will automatically populate the other category.

**Comment by polly64** [comment]
Also need 2 extra bands for age as follows
a) So keep as we have 'Year of construction' with earliest /latest options
b) _Add_ 'decade of construction' with dropdown options
c) Add 'century of construction' with dropdown options
Suggested by GLA and really good idea as may be a lot of difference of opinion about date and means that we can populate the simplified categories much more quickly 
Also so if a)  is given,  it will automatically populate  b) and c) 
Also add optional age category on Key- so we have by every 50 years as follows
Pre 1700, 1700-1749, 1750-1799, 1800-1849, 1850-1899, 1900-1949, 1950-1999, 2000- present

**Comment by dominijk** [comment]
@polly64 Confirming this, we currently have last major retrofit option in Energy/Sustainability category and the demolition pairs, we also have change of use date in type. We don't currently have a major extensions option to track that part of the building history as your first point. Age seems the logical place to capture this user flow would be has this building had a major extension (Default no with our definition of major) if yes how many, then inputs appear for the number you've given (up to 5) into which you can input year only (?)

**Comment by polly64** [comment]
i think this is where we really  need to cross reference . 

For demolition pairs keep in Age/History but also cross reference if you can to Planning as we want to track all new demolitions in the latter section . (Eventually we want a system where Construction date - as soon as combined with a demolition date - will generate 'lifespan' data for that typology.  But this is post Oct issue). 
Last major works -  I think this should have its primary position in 'Planning' . Eventually all extensions can presumably  link into the GLA's new planning portal which will provide details of works, or into NHLE entries.   Can this be cross referenced into a) Age/History, and b) Sustainability- so there is a link that will take you into planning to add the data?  yes fine to have  a) up to 5 only b) input year only.
Let's call it upgrade/extension works to get round major works issue
