### ISSUE TITLE
Add INSPIRE polygons as optional layer- longer term

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#240]
As I'm finding land parcels to be so important as a spatial unit of aggregation for resilience and vulnerability in the stock it would be good to have this an optional layer (with night/day).- if we could  overlay these polygons in a colour over the OSMM footprints. These can't be offered as a download  easily because of a third party restriction on INSPIRE though if this changed we could. This also links to the ownership section discussed in issue 108 #108

**Comment by matkoniecz** [comment]
now it is tracked as #796
