### ISSUE TITLE
UI/UX: Draw boundary lines around conservation areas

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#242]
hi Dom think these conservations areas are going to need boundaries to be more clearly defined, could u possibly put on april to-discuss list?. Also notice that we may have to clean up the data quite a lot as some of the LA datasets have missed quite a lot of buildings.

**Comment by tomalrussell** [comment]
Recommend not adding additional geometries to the site - we've got plenty to collect if we focus on building data, and a clean method for plotting buildings. 

We could look at colouring different conservation areas differently - this would give a clearer impression of the area boundaries.

**Comment by polly64** [comment]
interesting thought, let's talk more with Dom when he restarts in June and look at same time at colour coding of listed buildings grades - now we have the split entry version coming soon from Historic England

**Comment by dominijk** [comment]
Coming back to this one, now that we won't colour the buildings but would like to colour the areas. I'm going to test a few options but these involve an underlay with opaque/hatched fill which shows . the extent of the area. @tomalrussell Can you point me in the direction of the Maptile docs or comment on the feasibility of these appraoches

**Comment by tomalrussell** [comment]
The rendering docs for Mapnik are on their wiki:
- overview: https://github.com/mapnik/mapnik/wiki/XMLConfigReference
- polygons with plain fill: https://github.com/mapnik/mapnik/wiki/PolygonSymbolizer
- polygons with pattern fill: https://github.com/mapnik/mapnik/wiki/PolygonPatternSymbolizer

It would probably be simpler to use GeoJSON - probably cached on the server if that's feasible so we don't depend directly, but direct is an option. Then we could do similarly as we do with the GLA outline and render in the front end only (using [leaflet](https://leafletjs.com/examples/geojson/)).

**Comment by mz8i** [comment]
Presumably then, the fields for conservation area should be deactivated in the frontend? I assume we are going to automatically populate this data for the whole spatial extent of a conservation area, and editing the area name for a single building doesn't make sense any more, since it wouldn't be reflected in the colour map anyway?

**Comment by mz8i** [comment]
Another question, are conservation areas actually contiguous? As in, can they be visualised on a map as a single polygon? If not then that could potentially make it a bit complex to visualise on borders where to areas touch. To give an example from a different domain - postcodes are often loose groupings of buildings in a neighbourhood, and often can't be visualised very nicely on a map. But I'd assume conservation areas are more well-formed

**Comment by polly64** [comment]
Emailing you now two contacts at Historic England in GIS in case you want to email them

**Comment by tomalrussell** [comment]
Agree that this raises plenty of questions.
- are we "just" adding layers to the map for context (admin boundaries, possibly conservation areas)? 
  - this seems useful but raises questions of visualisation (as in @mz8i's second point above). We've done well to constrain the scope to buildings+backgroud, it keeps the visualisation design clean and concise.
- are we suggesting that the data collection aspect of the site should extend beyond "attributes of buildings" to include other areas/zones and their attributes? 
  - this would be an enormous increase in scope
- if we show conservations areas on the map as polygons, is it worth having any data regarding them at the building scale? (I think this is @mz8i's first point above)

I think we were onto a good thing with colouring the buildings individually: it's in keeping with the rest of the site visually; data entries can be edited and updated manually or automatically; the data is created at the building level - it says "this building is in this conservation area", which is slightly different from "this conservation area has this extent".

**Comment by mz8i** [comment]
Yes that's what I meant @tomalrussell  re your final bullet point - if we are collecting boundaries for conservation areas, does it make sense to edit that data for an individual building any more?

An alternative worth considering: treat the conservation area name as a categorical label, and just colour all the buildings according to the name of the conservation area they are in. This way we keep data on a building level, but the visualisation is more useful because it actually shows all the distinct areas rather than just a true/false value (is the building in any conservation area?)

**Comment by polly64** [comment]
Yes different colours  would perhaps work best .  The single colour is problematic because it means that you can't tell where the conservation areas starts and ends which will be needed by many types of user. Dom did look at this before  as attached.  I was concerned at the lack of clarity and overfussiness of multicolouring especially as we need to show lots of additional coloured data  cats e.g listed buildings etc at building level.  Do you want to try out recolouring the buildings within the areas but with a very subtle neutral scheme. Or could we colour the CA buildings white say and another colour if the buildings were within a radius of the boundary line so these would be highlighted r - again i think anther suggestion of dom's . Might be very hard to do though.  Also there was an before  of some of the buildings within the CA not being coloured.  Everything within a CA boundary will be designated. 

![Screen Shot 2018-12-02 at 21 30 08](https://user-images.githubusercontent.com/42236514/72728275-e7dd8e00-3b84-11ea-94a9-007b32d9fb4a.png)

**Comment by dominijk** [comment]
I'm with @tomalrussell on this. I don't think we should collect/show geometries. I also agree that the current way we visualise this isn't quite right. Switching to a limited colour palette that shows where one boundary stops and another starts would allow us to continue mapping by building whilst conveying the boundary extent. As the above highlights showing the conservation areas places emphasis on larger ones, in practice these might cover fewer buildings than more central ones. We shouldn't need a colour per area just away of figuring out how many colours we need to prevent two of the same colours touching. @mz8i not sure I completely understand your point on contiguous but I imagine the polygons are not very clean so two adjacent areas might have gaps and overlaps

**Comment by polly64** [comment]
@dominijk  hi, think the map has to be able to give an overview of constraints on dynamic behaviour / the extent to which changes to specific buildings and areas, and the speed of at which this change occurs is controlled .  Conservation areas are a very important part of this discussion as they are the main  and most effective mechanism used to calibrate rates of change. So I think it's important to see each category as having equal status. (Locally listed buildings are also interesting as they show people not only which buildings communities think work especially well but also the next cohort of stock where change is likely to be slowed.)  Given the above discussion I think for the moment   if we can't do an outline I would say let's go back to having just a pale colour (as we had green before) for all buildings in the CA but also give already coloured e.g LBs, locally listed etc an outline of this colour if they are in the CA.  I think we will probably need to do a bit of testing here and I may need to rework LB colours but @mz8i  could we possibly try with CA buildings White with a fine grey outline - which would make LB's etc also have fine grey outline if they were in a CA?

**Comment by mz8i** [comment]
@polly64 is the goal still to visualise if the building is listed and in a conservation area at the same time? Or is this superseded by the colour scheme for #538 ?

**Comment by polly64** [comment]
yes we need to do this - thank u just reminded me of this problem - so we need some clever way of having a building with a border round showing it's listed and in a conservation area, but at the same time allowing this border to show up next a building coloured just with the conservation area colour- so not easy do send across any thoughts any time


Polly Hudson

Senior Research Fellow

Director - Colouring London https://colouringlondon.org/

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ



________________________________
