### ISSUE TITLE
Menu redesign

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#264]
[Edited 4/10/19 to suggest that this be taken as part of a main menu redesign]

Main menu should link to:
- main features
  - View/Edit Maps
  - Downloads
  - Showcase
  - Leaderboards
  - Discuss
  - Log In, Sign Up // Account
- major info pages
  - About
  - Data Categories
  - Who's Involved
  - Data Ethics
- categories 
  - all 12 boxes
- minor info pages
  - Contact
  - Privacy Policy
  - Contributor Agreement
  - Code of Conduct
  - Data Accuracy Agreement
  - Ordnance Survey terms of UPRN usage

---
Below is the original draft for landing page Menu done with louis for the exhibition , would be good to now introduce this along with new draft logo- so we get clear branding message across 
Would be good to land on this page after main landing page  (and/or straight after sign up) so can choose to go straight to View or edit and see we will have Download and showcase but with hover showing they're coming soon.  I think it's important as it allows us to show whole platform strategy scope in one go - and to advertise major forthcoming features. 

Attach image - Louis can send logo
[190503_Colouring London PAGE 2.pdf](https://github.com/tomalrussell/colouring-london/files/3144472/190503_Colouring.London.PAGE.2.pdf)

**Comment by dominijk** [comment]
@polly64 Does this come after this page? 
<img width="1064" alt="Screen Shot 2019-07-01 at 18 08 56" src="https://user-images.githubusercontent.com/6041913/60454276-54b22a80-9c2b-11e9-926b-ca8add4b3800.png">

**Comment by tomalrussell** [comment]
Closed by #564
