### ISSUE TITLE
Move construction and demolition site pairs from 'Demolition' to 'Age'

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#266]
1.' Demolition' category to now be used to highlight  buildings under threat and identify recently demolished 
ai) is there a threat of demolition to this building?
aii) url link to enable community to comment
b) Is there a planning application /demolition permit submitted
c) Has this been demolished recently (last 6- 12 months)

2.  'Age' 
Add construction and demolition site history pairings from 'Demolition' category to 'Age'
Find way to i) trigger user to add new entry for building age ii) autoshift current building age and associated data of demolished buildings to demolition and construction site history pairings section

**Comment by dominijk** [comment]
Check meeting notes for what was agreed on demolition

**Comment by dominijk** [comment]
Demolition now under planning, how does pairing function work and what is it attached to that will be visible.

**Comment by polly64** [comment]
see Building categories page sub categories for what is included where or drop me another line if not clear


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ




________________________________

**Comment by tomalrussell** [comment]
Construction/demolition pairs are not yet developed - suggest using a jsonb field with a list of (construction year, demolition year) pairs of integers. This would be similar approach to the list of text links under age.
________________________________

**Comment by polly64** [comment]
demolition will also need to synched to planning where it will also be shown


Polly Hudson

Doctoral researcher (EPSRC DTG)

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ




________________________________
