### ISSUE TITLE
BulkData: Accessibility

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#315]
It would be good to talk about data on buildings and disabled access

**Comment by dominijk** [comment]
@polly64 I've asked Livy to look into what data is held on this and any standard categories and sent those I know of. It's a great one for us to crowd source as there's a genuine lack of data around this. I can see a challenge here in that this really applies to premises more than buildings ie. You might be able to access the ground floor if it's street level but no subsequent floors or it might be accessible but not have accessible facilities (WC etc), so we will need to clear on what we saying. Which seems like it will be, can you get into the building?

**Comment by polly64** [comment]
thanks Dom it would also be good to involve any organisations working specifically in this area as well as accessing datasets just to look at other isues going forward.  I think can u get into the building is the main question we are able to ask because of our currently informal privacy policy of not collecting data on the interior of buildings

**Comment by dominijk** [comment]
@polly64 Thanks I have a couple of leads but will keep collecting with LG and then review with you in a week or two

**Comment by dominijk** [comment]
@polly64 Shall we add accessibility to the location category? With drop down options as defined in [wheelmaps](https://wheelmap.org/)? 

1. Wheelchair accessible 
2. Partly wheelchair accessible
3. Red not wheelchair  
4. I'd suggest an extra one for ambulant disabled 


We won't use those colours as they are not accessible for colour vision deficient persons. The map is powered from [accessibility](https://www.accessibility.cloud/) cloud via an api. Their approach to locked data is also interesting, they're a crowd sourcing platform generally so anyone can contribute but datasets provided by trusted partners on accessibility cloud are locked and cannot be edited.
