### ISSUE TITLE
Cross reference awards, certificates in 'Energy' with 'Team'

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#351]
So that a team's awards in terms of sustainable design can be seen/celebrated straightaway along with their profile - not urgent

**Comment by dominijk** [comment]
@polly64 When we say team here we mean the design team rather than volunteer team i.e. I'd see Richard Rogers - n Awards for buildings in the GLA?

**Comment by dominijk** [comment]
@tomalrussell Getting my head round the code base would this be something like the `get buildings` call but return `design team - architect/engineer/etc`

**Comment by tomalrussell** [comment]
I think all the data is still going to be stored on the building, so we might have something like:
```
{
  'design_architect': 'Fantastic Architects Ltd'
  'design_builder': 'A. Brown & Partners'
  ...
  'energy_epc_rating': 'A+++++',
  'energy_sustainability_award': 'Certificate of excellence in sustainable design and build'
  ...
}
```

And if I understand right, @polly64's suggestion is that any certificates or awards (assuming we're collecting this data and it's present for this building) which may be entered in the 'Energy' section, should be repeated when reading the 'Team' section.

So technically this would be entirely front-end. We've already got all the building's data to hand when rendering any section. Would need to add a special case in the 'Team' section to include that extra info.

**Comment by dominijk** [comment]
I'd read it as being able to access the team on another page and see total number of awards attached to all buildings. Equivalent to a query that returns top 10 architects for awards

```sql
SELECT
Sum (energy_awards + design_awards) as total_awards
FROM buildings
GROUP BY designteam_architects
ORDER BY total_awards DESC 
LIMIT 10

--returns

star_architect 100
next_best 90

```

**Comment by tomalrussell** [comment]
One to wait for clarification on, then.. :slightly_smiling_face: - that's a plausible approach, but that kind of analytic query is relatively more expensive, might be something to do under a separate banner (and include in showcase) or consider alongside other stats/analysis stuff we might update less-than-live.
