### ISSUE TITLE
New sub category:  'Healthy material' rating greyed out

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#352]
Hi i think we should also get people to start getting people about  mappings toxicity ratings for building materials- as well as  safety .  Interesting article Health anf th Building stock by E Haaselaar https://www.tandfonline.com/doi/full/10.1080/09613210903186836

**Comment by dominijk** [comment]
I think i'd suggest we automatically generate this in conjunction with the primary and secondary materials. Given our general approach to capturing data on the external envelop this should be acheivable.
