### ISSUE TITLE
UI/UX: Pre-populate URL for NHLE and planning database

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#354]
Hi Dom for launch can we prepopulate main planning portal url link for every building?  Once GLA have their new system up and running it would be great to try and link for specific address for each - and their historic applications to be included - but would be nice to just show this connection to regulatory framework for Oct. have we time to do for NHLE link too presume too hard to add individual NHLE address links?

**Comment by dominijk** [comment]
@polly64 Thoughts on this;

- We could pre-populate with **either** https://maps.london.gov.uk/map/?ldd **or** individual borough planning portals. My preference would be the single GLA one as the boroughs involve spatial analysis to attach the boroughs to the buildings. The boroughs have more historic detail though. 
- For NHLE we could start with the general link then when we get UPRN for the list we can update the links to go to the list page.

With any of the links we are reliant on them being static, ie if the boroughs change them they will break. We experienced this at Energy where MHCLG updated the links and reference number two weeks ago breaking our website.

**Comment by polly64** [comment]
great - yes the single gla one sounds good though looks as though we'd have to keep an eye on when their update was happening. NHLE general good for moment just to show people it's there
