### ISSUE TITLE
Can we have under 16 needs guardian signature on the sign up?

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#385]
Hi Is this standard on other sites?

**Comment by tomalrussell** [comment]
We should limit sign up to people over the age of 13.

ICO guidance on GDPR [1] age of consent is that children over the age of 13 are able to provide consent; below that age you need to get consent from whoever holds parental responsibility for the child.

[1] https://ico.org.uk/for-organisations/guide-to-data-protection/key-data-protection-themes/children/

**Comment by polly64** [comment]
ok thanks if we can do that that would be great
