### ISSUE TITLE
Revise contributor agreement and/or introduce code of conduct

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#391]
Do we have anything in the sign up stating that malicious uploads will result in the deletion of accounts and that is at our discretion?

**Comment by tomalrussell** [comment]
Not at present.

Our contributor agreement focusses on data contributions: https://colouring.london/contributor-agreement.html

On the discuss forum we have some guidelines: https://discuss.colouring.london/faq

Here are a couple of options suggested by GitHub's guidelines for project code of conduct:
- recommended for projects of any size: https://www.contributor-covenant.org/version/1/4/code-of-conduct
- recommended for larger communities and events:  http://stumptownsyndicate.org/code-of-conduct/

The first should be easy to put in place; the second would require a bit more organisational structure first.
