### ISSUE TITLE
revised view map & titles  interface visual

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#490]
![revised draft](https://user-images.githubusercontent.com/42236514/68393284-a16eba80-0163-11ea-8f12-d1c737063d22.JPG)
category info margin widened to accommodate clickable category/logo. Avoids backspace.  needs to be wide enough to be legible. Top bar moved to menu box- n(eeds icon and text description) following tom thought we could gain more space losing it completely.  key made narrower. Category highlights when clicked and categories open below.  Category box stays in place so you can easily add more data for building. logo shrunk on key. Do add comments

**Comment by tomalrussell** [comment]
I like the overall look of this. A couple of things to consider:
- main menu button needs to be super clear: could be wider and moved tighter into the top-right corner; could consider putting it top-right within the sidebar?
- the current sidebar header has a few important user-interface bits (info/history/edit/copy/cancel/save): could put below the category grid in a grey-background bar?

**Comment by polly64** [comment]
ok will revise tonight thanks tom

**Comment by polly64** [comment]
more like this? 
![version 2](https://user-images.githubusercontent.com/42236514/68425217-90429f80-019d-11ea-93ab-0d3d2378b27a.JPG)

**Comment by polly64** [comment]
![Main category master see also wix](https://user-images.githubusercontent.com/42236514/72071470-ca3a3a00-32e3-11ea-882a-b6856da2f564.JPG)

Revised main category titles
