### ISSUE TITLE
solution re  colouring london name/logo slicing off on screenshots?

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#495]
Hi any thought on how we  can encourage people to include the logo - i just noticed this at an event i'm talking at on 9th dec and it's all been sliced off. 

![Capture](https://user-images.githubusercontent.com/42236514/68599493-9041e880-0498-11ea-8ee5-03115374f4de.JPG)

**Comment by dominijk** [comment]
@polly64  One quick solution here would be to have a pack of graphics people can use which include the logo and anything else we want and make that the easiest thing for people to do. Incidentally this is the conference we were suggested to put our map in for London map of the year.

**Comment by polly64** [comment]
ok this is the conference i'm talking at. I think we should hold off going for prizes yet.  I think we probably need to monitor our logo quite tightly otherwise we might find in shoved on stuff we don't think's good. I think we need to keep it also to show we're partnering with a specific organisation e.g ODI and Colouring Beirut. Happy to see people reusing maps with logo on them but just not logo on its own. Let's talk more.
