### ISSUE TITLE
Initial user leaderboard

### ISSUE THREAD

**Issue by tomalrussell** [colouring-london/colouring-london#496]
Towards #48 - first implementation.

- create API endpoint to query contributions
- count contributions simply as number of entries in edit log
- create a new page with table of top 10 all-time contributors

Rank | Username | Contributions
--- | --- | ---
1 | abc | 1234
2 | zzz | 23
... | ... | ...

- add switch between showing top 10/100 
- add switch between showing contributions in the last 7 days/30 days/all time

**Comment by martin-dj** [comment]
I'll have a go at this issue as I've already created the appropriate SQL query to generate some stats for Duncan's Innovate meeting.

**Comment by tomalrussell** [comment]
Basic leaderboard available at https://colouring.london/leaderboard.html
