### ISSUE TITLE
UI/UX: Landuse category - Activate maps

### ISSUE THREAD

**Issue by dominijk** [colouring-london/colouring-london#513]
**Dependencies**
- [ ] Run migrations, see linked issue #358 

**What UI does**
Allows inputs for `landuse_class`, this might be single or multiple for a building. As #365 this will be a large list and to assist users we wants them to type in a keyword and then get back a list of possible `landuse_classes`. Nice to have here is to then autopopulate the `landuse_order` on save. The field will want a source. 

**What map looks like**
On load, category visualisation is `landuse_order`. ~~Initial colours below taken from colour brewer @polly64  please review these and inputs section below.I've set some values as transparent as I wouldn't expect them to occur on buildings, we can omit them from the map legend but they will exist in the database for future flexibility~~. @mz8i the table below has been updated with the latest colour values;

|landuse_id|description|colour_hex_value |
|----------|-----------|--|
|U010|Agriculture And Fisheries| `#52403C` |
|U020|Forestry (not used) |`#AARRGGBB ` |
|U030|Minerals (not used) |`#AARRGGBB ` |
|U040|Recreation And Leisure| `#ffbfbf`|
|U050|Transport| `#b3de69` | `#bee8ff`|
|U060|Utilities And Infrastructure| `#cccccc`|
|U070|Residential| `#4a54a6` |
|U080|Community Services| `#73ccd1`|
|U090|Retail| `#ff8c00` |
|U100|Industry And Business|`#f5f58f` |
|U110|Vacant And Derelict| `#ffffff`|
|U120|Defence| `#898944`|
|U130|Unused Land (not used)|`#AARRGGBB ` |
|U140*|Mixed Use| `#e5050d` |

* This is not an NLUD category but there's no mixed use which we need for buildings. 

**Inputs on edit UI**

category | field label | tool tip | db_field | active | input_type | data_type / constraint
-- | -- | -- | -- | -- | -- | --
Landuse | Landuse class: What is the building used for? | Add one or more uses for the building | current_landuse_class | yes | Autocomplete | ENUM (see separate file 500+ values)
Landuse | Landuse order | Each landuse class belongs to an order, we automatically add this here | current_landuse_order | yes but not user editable | machine filled | ENUM as visualisation values

**Comment by polly64** [comment]
Hi Do, I'm seeing Tarn next week to talk colour so would just put up whatever you think and we'll then review. There are some categories that we aren't using and therefore don't need to be in . These are Forestry and Minerals.  i think i only had only a couple of entries for agriculture and fisheries and that was a vet's surgery and a city farm - could u possibly check those one's again- the title is very confusing and should go towards bottom of key. Key best to run by rough order of frequency so ideally

Residential
Retail
Industry and Business
Community Services
Recreation and Leisure
Transport
Utilities and Infrastructure
Defence
Vacant and Derelict
Unused land

For mixed use were we having a is it mixed use at start and then they put in both?

**Comment by dominijk** [comment]
@polly64 Can you clarify what you mean by "the title is very confusing and should go towards bottom of key" ? Mixed use will be generated by the computer if a user adds more than one use for the building. As discussed the user will add from the landuse class list but the map will visualise the landuse order.

**Comment by polly64** [comment]
i meant agriculture and fisheries if we have to use it

**Comment by dominijk** [comment]
@polly64 On your previous query, Veterinary would fall into `Agriculture And Fisheries` as would a few other agriculturally related building types which we could have. So we will need a colour for this landuse order

**Comment by polly64** [comment]
Colour key for land use map RGB and CMYK

Community services 
R=115, G=204, B=209
C=55, M=20, Y=18, K=0

Defence
R=137, G=137, B=68
C=46, M=46, Y=73, K=0

Industry and Business
R=245, G=245, B=143
C=4, M=4, Y=44, K=0

Mixed 
R=229, G=5, B=13
C=10, M=98, Y=95, K=0

Recreation and leisure 
R=255, G=191, B=191
C=0, M=25, Y=25, K=0

Residential
R=74, G=84, B=166
C=71, M=67, Y=35, K=0

Retail
R=255, G=140, B=0,
C=0, M=45, Y=100, K=0

Transport
R=190, G=232, B=255
C=25, M=9, Y=0, K=0

Utilities
R=204, G=204, B=204, 
C=0, M=0, Y=0, K=20

Vacant and derelict - white

**Comment by mz8i** [comment]
Are these values different than the ones in the initial description above?

**Comment by tomalrussell** [comment]
Yes - rgb to hex for Community Services is `rgb(115, 204, 209)` == `#73ccd1`, as opposed to `#fb8072`  above

**Comment by polly64** [comment]
Ok it’s literally three buildings so just go for any brown U like at the moment. Once colours are up and can test I will revise with tarn in new year thanks dom
Polly Hudson
Senior Research Fellow
Director - Colouring London https://colouringlondon.org/
Bartlett Centre for Advanced Spatial Analysis
University College London
90 Tottenham Court Road W1T 4TJ


________________________________

**Comment by mz8i** [comment]
@polly64 @dominijk what is the order of values we'd like to have in the legend? Going to go for alphabetical now, but please consider ordering in terms of importance / likelihood to appear in a city. Otherwise, Agriculture and Fisheries is at the top of the list... ;)
