### ISSUE TITLE
colour keys for age maps

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#525]
New colours for 2 x categories CL age map as some needed enriching for better user 'thank you' and also we are likely prepopulate residential categories for semi detached and victorian (me working with Flora who's at turing). I'm also merging 3 categories as unnecessarily detailed

So 1880-1899 changes to  
C=20
M=72
Y=44
K=21
or R = 150, G = 18, B=89

1860-1879 changes to
C=71
M=67
Y=35
K=0
or R=72, G=84, B=166

Merge 1800-1819 with 1820-1839 same colour as Tarn's original colour for 1780-1800

Merge all categories from 1700-1799 and make same colour and rename 1700-1799. Use Tarn;s original 1760-1780 colour

Merge all categories from <1699 and make the colour of this category white

**Comment by polly64** [comment]
hi Maciek can u also adjust the dates - sorry they should  read 1920- 1929, 1930-1939 etc not 1920-1930, 1930-1940

**Comment by mz8i** [comment]
Hi @polly64 by Tarn's original colour for 1760-80 do you mean the current colour for that range?

**Comment by mz8i** [comment]
@polly64 I have implemented the changes, but need to consult a few things before releasing

1. the first new colour you gave, the CMYK colour doesn't match the RGB colour (see below) - which one to use, the RGB definition or CMYK definition? It's a small but visible difference.
`rgb(161, 56, 113)` ( = cmyk(20%, 72%, 44%, 21%))
`rgb(150, 18, 89)`

2. that's how the legend looks after the colour scale changes (no adjustment yet to 1920->1919 etc):
![image](https://user-images.githubusercontent.com/36160844/74042829-2d40ee80-49c0-11ea-8e3f-c85eeae31b3e.png)
Is this the desired progression? At first sight it looks a bit like 1840-1860 and 1860-1880 were meant to be swapped?
3. I think in another discussion @polly64 you were saying we shouldn't use white colour because it is difficult to see on the light style background (see St Paul's Cathedral below). Do we want to stick to white as the oldest colour?
![image](https://user-images.githubusercontent.com/36160844/74043122-bb1cd980-49c0-11ea-98d0-4e9734bc2a27.png)


@tomalrussell I assume that after the change, we need to purge the tile cache for the whole category? We might want a script to re-cache a certain region, e.g. overnight - for changes like this and for new categories (before releasing)

**Comment by mz8i** [comment]
And last question. Upon changing "end" dates, it feels to me that the legend in such a form, while technically more correct, is actually harder to read for the user. The only confusion can arise in the edge cases, but 
I'd suggest keeping the original format of the legend ranges. See comparison below:

before             |  after
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/36160844/74043558-81989e00-49c1-11ea-84cf-cfaf9b9cd249.png)  |  ![image](https://user-images.githubusercontent.com/36160844/74043541-7ba2bd00-49c1-11ea-8dea-ab3110c84d33.png)

**Comment by polly64** [comment]
Yes
Polly Hudson
Senior Research Fellow
Director - Colouring London https://colouringlondon.org/
Bartlett Centre for Advanced Spatial Analysis
University College London
90 Tottenham Court Road W1T 4TJ


________________________________

**Comment by polly64** [comment]
@mz8i sorry I don't know why I wrote yes! this was meant say that actually I think though agree it is hard to read think it does need to be change it to the 1700-1799. the alternative would be to put an ' s' on everything after  1800-1839e.g 1840s, 1850 etc. This might actually be the clearest , shall we try?

**Comment by polly64** [comment]
@mz8i   
in reply
a) yes absolutely could u put border round white as for scheduled monuments.
b) ok so looking at this now think need readjusting 
so can u
i) keep 1920 to 2000 a it is 
ii) for 1900-1919 replace the red with the purple i.e. change to rgb (150, 18, 89)
iii) make 1880-1899 =make R=48,111,199
iv) make 1860-1879= keep as is
v) make 1840 - 1859 -= make R=20 G=36 B=166
vi) keep  1700-1799 and 1800-1839 as they are 
may need to make further adjustments but this  now right number of classes i think,  and right grouping, and right range of colours. just might need tweaking of tones of blues by tarn.

**Comment by polly64** [comment]
thanks will send to tarn for comment, I think we probably need to make the blues going light to dark going downwards but will talk to tarn today

**Comment by polly64** [comment]
...........Draft only    I've been looking again at age as we're going to be uploading so much - and this is our main source of images  for publicity and I've revised it again so we have a new key that's not as long as original (and doesn't need to scrolled down on) but is more detailed than simple one as close up it's interesting to see how diverse areas are. We can go through in the meeting as it's quite fiddly but here are the final categories:

21st Century (yellows
          >2020  (Lighter yellow: new colour)
            2000-2019 (Darker yellow: same colour as on short key on staging for 1980)

Late 20thc century (oranges)
           1980-99 (Lighter orange- same colour as short key for 1960)
           1960-79 (Darker Orange- same colour as short key for 1940)

Mid 20thc/Interwar and early postwar (reds)
           1940-59 (Lighter red - new colour)
           1920-39 (Darker red - new colour)

V. early 20thc/Edwardian/ (purples)
           1900-1919 (Purple - same as short key)

Mid-late 19thc/Victorian/ (blues) 
           1880-99 (Light blue - new colour)
           1860-79  (Mid blue - new colour)
           1840-59) (Dark blue - new colour)

Early 19thc/Late Georgian (Turquoises)
          1820-39  (Lighter turquoise - new colour)
          1800 -19 (Darker Turquoise - new colour)

18th century/Early to mid Georgian (Greens)
          1750-99  (Lighter green)
          1700-49  (Darker green)

<1700
         <1700 (Pale Brown same as 1680-1700 on long age key/live site )

Tarn and I were looking at Bert Spaan's map https://code.waag.org/buildings/#52.3719,4.9423,12 and she was noticing how it is a pure black background so everything stands out v clearly whereas ours is more a blue with a number of dark colours for roads and other features etc. This might also be adding the problem of the colours fading out when you're zooming out - as bright colours just start to look grey.  The other option would to, if u can do this make it so the colours begin to aggregate as u zoom out? I think I actually remember tom talking about this a while ago. Anyway let's chat

**Comment by mz8i** [comment]
@polly64 could I ask you to edit the following comment and fill in the required colours in hex format, by replacing each `#ffffff` (white) placeholder with the right hex code e.g. red = `#ff0000`? If we use this format consistently for this and other colour scales, it will greatly increase the speed of working with colour changes, especially if we need to do some further tweaks.

**Comment by mz8i** [comment]
If there should be no border for a given row, please leave the last column blank.
The upper bound specified in the `to` column is exclusive - this is reflected in the labels.

| from | to | label | colour | border
| -- | -- | -- | -- | --
| 2020 | | >2020 | `#ffffff` |
| 2000 | 2020 | 2000-2019 | `#ffffff` |
| 1980 | 2000 | 1980-1999 | `#ffffff` |
| 1960 | 1980 | 1960-1979 | `#ffffff` |
| 1940 | 1960 | 1940-1959 | `#ffffff` |
| 1920 | 1940 | 1920-1939 | `#ffffff` |
| 1900 | 1920 | 1900-1919 | `#ffffff` |
| 1880 | 1900 | 1880-1899 | `#ffffff` |
| 1860 | 1880 | 1860-1879 | `#ffffff` |
| 1840 | 1860 | 1840-1859 | `#ffffff` |
| 1820 | 1840 | 1820-1839 | `#ffffff` |
| 1800 | 1820 | 1800-1819 | `#ffffff` |
| 1750 | 1800 | 1750-1799 | `#ffffff` |
| 1700 | 1750 | 1700-1749 | `#ffffff` |
|  | 1700 | <1700 | `#ffffff` | `#ffffff`

**Comment by polly64** [comment]
Hi Maciek
a) no borders on any- only the border allowing u to see the building is separated from the next
b) do u have a list somewhere of hex numbers for the long key on the live site so i can transfer as i don't have these hex numbers?


Polly Hudson

Senior Research Fellow

Director - Colouring London https://colouringlondon.org/

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ



________________________________

**Comment by mz8i** [comment]
Sure, this is the current live scale:
| from | to   | colour    |
| -    | -    | -         |
| 2000 |      | `#f0eaba` |
| 1980 | 2000 | `#fae269` |
| 1960 | 1980 | `#fbaf27` |
| 1940 | 1960 | `#e6711d` |
| 1920 | 1940 | `#d73d3a` |
| 1900 | 1920 | `#ba221c` |
| 1880 | 1900 | `#bb859b` |
| 1860 | 1880 | `#8b3654` |
| 1840 | 1860 | `#8f5385` |
| 1820 | 1840 | `#56619b` |
| 1800 | 1820 | `#6793b2` |
| 1780 | 1800 | `#83c3b3` |
| 1760 | 1780 | `#adc88f` |
| 1740 | 1760 | `#83a663` |
| 1720 | 1740 | `#77852d` |
| 1700 | 1720 | `#69814e` |
| 1680 | 1700 | `#d0c291` |
| 1660 | 1680 | `#918158` |
|      | 1660 | `#7a5732` |

**Comment by polly64** [comment]
perfect


Polly Hudson

Senior Research Fellow

Director - Colouring London https://colouringlondon.org/

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ



________________________________

**Comment by polly64** [comment]
can i just also have the 1900 purple hex from the short key on staging?


Polly Hudson

Senior Research Fellow

Director - Colouring London https://colouringlondon.org/

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ



________________________________

**Comment by mz8i** [comment]
The current key on staging has the same purple colour for 1900 as the live site: `#8f5385`

**Comment by polly64** [comment]
i think  1900 is a bit more a red on the live site.  This one you've sent looks a bit pale compared to what i thought it would when i write it in which is a bit odd  -  could u possibly double check its the number for 1900 on staging? If it is i might find another


Polly Hudson

Senior Research Fellow

Director - Colouring London https://colouringlondon.org/

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ



________________________________

**Comment by mz8i** [comment]
@polly64 re the borders aiding visual separation of same-color buildings, what color are we thinking of for the border?

**Comment by polly64** [comment]
@mz8i i though the way you showed it to be in the previous border demo link u sent  looked really good- did u use a grey?

**Comment by mz8i** [comment]
@polly64 my memory must be failing me because I don't remember us trying any such border... The one we did try was the colourful border for conservation areas, but that was in the conservation area colour, not a universal one.

**Comment by polly64** [comment]
my fault yes it was conservation areas- yes just like this in terms of colour but i think actually very slightly thicker as it's slightly difficult to see. 

Yes u r right we need to look at a few of these colours again - dark red and purple too similar and the turquoise is getting muddled with blue and needs to be more green.  I'll take a screen shot and send  tarn and then will adjust on master templete above. Ru working on monday?

**Comment by polly64** [comment]
from | to | label | colour | border
-- | -- | -- | -- | --
2020 |   | >2020 | #fff9b8 |  
2000 | 2020 | 2000-2019 | #fae269 |  
1980 | 2000 | 1980-1999 | #fbaf27 |  
1960 | 1980 | 1960-1979 | #e6711d |  
1940 | 1960 | 1940-1959 | #e65b29 |  
1920 | 1940 | 1920-1939 | #c20404 |  
1900 | 1920 | 1900-1919 | #8f5385 |  
1880 | 1900 | 1880-1899 | #c3e1eb |  
1860 | 1880 | 1860-1879 | #6a9dba |  
1840 | 1860 | 1840-1859 | #3b74a3 |  
1820 | 1840 | 1820-1839 | #95ded8 |  
1800 | 1820 | 1800-1819 | #68aba5 |  
1750 | 1800 | 1750-1799 | #acc98f |  
1700 | 1750 | 1700-1749 | #6d8a51 |  
  | 1700 | <1700 | #d0c291

**Comment by polly64** [comment]
@mz8i  I've made some more structural revisions to the colours for the age so I can talk to tarn over weekend.  the approach i'm using just isn't really working so i'm going to have to just do by key periods when form/materials change rather than trying to do a parallel systemso u can read by century as well - just too complicated .  Could u possibly load these onto staging once the listed buildings are up many thanks
