### ISSUE TITLE
ODI Multiple open data certificate - sign up for

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#528]
could we sign up for this will be good to have as a trust mark https://certificates.theodi.org/en/

**Comment by dominijk** [comment]
@polly64 Have you reviewed whats involved in this, is it an administrative task or technical one? Could you also give an indication of priority for this task by assigning it to a milestone.

**Comment by polly64** [comment]
I can do it, just want to chat first re the multiple data aspect. If you're free thursday we can chat then
