### ISSUE TITLE
Enable street names to be read at close up level

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#53]
Users need to be able to read street names ( and as we said numbers when we have them) or think they will get v confused

**Comment by tomalrussell** [comment]
Relates to #54 and #11 - this might involve rendering street name labels in a custom basemap to fill in the high zoom levels (19-20) which are not covered by the OS basemap, which may take reasonably high effort.

**Comment by polly64** [comment]
Ok I think we will have to do this fairly early on as otherwise people will lost when they're filling.  It's already going to quite hard for a lot of people without numbers. Can you email me with an idea of how long willl take and I'll also plan trip to come up and see you.

**Comment by tomalrussell** [comment]
Closing in favour of #11
