### ISSUE TITLE
Colour key references: Primary materials and roof materials

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#539]
Colour key references for both Primary materials and roof materials as follows: if additional categories are required we can reassess scheme and add a colour.

name | rgb | hex
--- | --- | ---
Brick/Clay (Pink)   | `rgb(252, 168, 157)` |  `#fca89d`
Slate (dusty pink)  | `rgb(196, 138, 133)` |  `#c48a85`
Steel/Metal (Forest green)  | `rgb(92, 137, 112)` |  `#5c8970`
Timber (Brown)  | `rgb(150, 97, 59)` |  `#96613b`
Stone (kharki green)    | `rgb(181, 168, 89)` |  `#b5a859`
Glass (cream)   | `rgb(255, 255, 227)` |  `#ffffe3`
Concrete (duckegg blue) | `rgb(190, 255, 232)` |  `#beffe8`
Natural (including green roofs/thatch)  | `rgb(245, 217, 107)` |  `#f5d96b`
Ashphalt or other (DarkBrown/Purple)    | `rgb(77, 0, 0)` |  `#4d0000`

**Comment by dominijk** [comment]
Can we have the colours as a hex reference as this is what we use in the code, this is a nice website for converting and picking colours https://htmlcolorcodes.com/color-picker/

**Comment by polly64** [comment]
Hi Dom i have to use the arcgis system as I test them on the maps but think they have RGB, CMYK and HEX on it


Polly Hudson

Senior Research Fellow

Director - Colouring London https://colouringlondon.org/

Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ



________________________________

**Comment by tomalrussell** [comment]
Just updated - you can search directly for colours on https://www.colorhexa.com/

**Comment by dominijk** [comment]
@polly64 , @MeldaS and I reviewed the great work she has being doing around capturing materials from listed buildings. This raises a few questions on the above which need a review. For historic buildings we often have more than two primary materials due to incremental additions and organic growth through time. When we discussed yesterday we said we'd start by uploading just buildings that have one or two materials to get something onto the map. Our option then might be something like
- More columns called tertiary material 
- Single extra column which allows a list of extra materials.

Theres also a question for Historic England here on what the materials column means and how it's generated, is the order in which they've given their materials the order of importance or just a list. Does glass ever mean window or a full glass wall?

**Comment by polly64** [comment]
@dominijk @MeldaS thanks Dom im seeing melda monday so will have a look at this with her. I think the main thing is to separate the core construction materials from the extension materials. So in the computational generation we're doing with age we will be assigning typical core construction materials to each age cohort we release . Melda this will give u a lot of data over next few weeks. So perhaps- also thinking of retrofit agenda, and my work on age diversity and resilience to demolition, we might want to change the name from ' primary' materials to ' original core construction materials' or something equivalent .  Then have a second category celled 'Other construction materials' or 'Other materials'. We don't need to pick up glass unless part of the construction system as assumed it will be in all buildings- (also its in sustainability whether single /triple glazed etc). I think we can assume the vast majority of NHLE glass is non-structural.

**Comment by polly64** [comment]
@MeldaS @mz8i  There are  4 material sections we want to collect
a) Main structural material/s e.g brick, concrete, steel 
b) Additional materials e.g concrete extension to brick building
c) Cladding/render e.g pebbledash, stucco, mathematical tiles
d) Roof materials e.g slate, pantile, asphalt

However think best to just start with one i.e. main structural material.  This will allow us to pick up whether the house is mainly brick, concrete, steel etc and we want this to be pretty simple.  the vast majority of buildings under 6 storeys will be brick in London and over 5 storeys will be concrete or steel. Other materials will be pretty rare so initially i think we can group these and then we can separate out if we find we are collecting a significant number of one type. 

So i think we should start with testing the following options using colour scheme above 
Timber
Brick
Steel
