### ISSUE TITLE
ownership info

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#544]
‘Keep it in the Community’ new gov funded project which would link nicely with this.  RE gov owned assets Dom can you try Cabinet Office’s Government Property Unit re national asset spreadsheet– PIMS Property Info Management System.

**Comment by dominijk** [comment]
@polly64 Do you have have a link to this? 
Is this different from the GLA data on ownership (https://maps.london.gov.uk/LLC/ ) which shows local / central government ownership along with company ownership where held?

**Comment by tomalrussell** [comment]
I think this is the Government Property Unit: Electronic Property Information Mapping Service [e-PIMS](https://www.gov.uk/guidance/government-property-unit-electronic-property-information-mapping-service) - on data.gov.uk:
- [quarterly extracts to June 2016](https://data.gov.uk/dataset/17209eb1-98de-4b5c-ae49-258da9faeb0e/central-government-property-and-land-including-welsh-ministers-estate)
- [latest](https://data.gov.uk/dataset/c186e17f-654d-4134-aed7-b3f13469546a/central-government-welsh-ministers-and-local-government-including-property-and-land)

Data is from central government, so I'd guess it has some overlap with the data on the LLC map - mandatory updates from:
- government departments
- non-ministerial departments and their executive agencies
- arms length bodies
- non-departmental public bodies
- special health authorities

**Comment by dominijk** [comment]
For my reference this is the building and occupancy sheets as attached, this will be quicker to add than the LLC data links to https://github.com/colouring-london/colouring_london_analysis/issues/2
[Occupation.xls.zip](https://github.com/tomalrussell/colouring-london/files/4041955/Occupation.xls.zip)
[ePIMS_Building.xls.zip](https://github.com/tomalrussell/colouring-london/files/4041956/ePIMS_Building.xls.zip)

**Comment by polly64** [comment]
See also Dom's comments at Dependencies
Run migrations as #432 to enable input to db

What UI does
Allows input for three fields in category as below, allows multi copy;

Ownership type - drop down from 5 choices
Private individual
Private company
Private offshore ownership
Publicly owned
Institutionally owned
Ownership perception - Yes/No option
Historic ownership - Yes/No option
What map looks like
On load, category visualisation is ownership type. Initial colours as below;

Private individual - #aaaaaa
Private company - #f2a2b9
Private offshore ownership - #ab8fb0
Publicly owned -#57c28e
Institutionally owned - #6bb1e3
Remaining categories should overlay onto this. Ie hatch or symbol so you can visualise the current state and either/or of the others. @tomalrussell i'm new to mapnik would this mean adding a layer with transparent background or would it render a new tile with colour and symbol.
