### ISSUE TITLE
UI update: Landuse category

### ISSUE THREAD

**Issue by dominijk** [colouring-london/colouring-london#566]
@polly64 Anything else to add to this, wanted to confirm we are renaming the category in particular

- [ ] - Update category rename from `Landuse` to `Building use` 
- [ ] - Rename fields - will still point to same database columns;
   - Current Land Use Class > Current Building Use Class
   - Current Land Use Group > Current Building Use Group
   - Current Land Use Order > Current Building Use Order
- [ ] - Add user tips explain what a class is with example eg. Residential - Semi-detached house 
- [ ] - Add user tip to explain what a group is e.g. next level from above Residential -Dwelling - Semi-detached house
- [ ] - On legend, note legend coloured by `Building Use Order` which computer calculates using `class` and `group`
- [ ] - Show edit history on edit form (as with all) - long term feature upgrade see [discussion](https://colouringlondon.slack.com/archives/CM3PJTHQV/p1578654224024000)
- [ ] - Don't display derelict but collect completed via #564 on staging

**Comment by polly64** [comment]
looks good
