### ISSUE TITLE
Tabulate proposed method of updating/lifespan data

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#576]
@dominijk would be good with @MeldaS and @dining to begin to record how we're planning to update each subcat  so probably would be best to do on main excel sheet 
For example - age currently read ' annual demolition data generated from OSMM using method developed by Kimon krenz' .  Demolition data is the main way we will update occurring to a  building's core structure so we need to begin to think @tomalrussell @mz8i of how we could  automatically move attribute data of demolished buildings to the Dynamics section so it populates the construction history from which metabolism animations and lifespan data will be able to be generated.

**Comment by dominijk** [comment]
@polly64 I've put this onto a post March milestone to focus us on getting the remaining categories us in the first place. We don't have a main excel sheet if you do can you send to me and we will put it on the cloud with edit rights and tracked changes for everyone.

**Comment by polly64** [comment]
@dominijk yes great agree and  here it is
[Sub category notes dropdowns for dom jan 3rd 2020.xlsx](https://github.com/tomalrussell/colouring-london/files/4203512/Sub.category.notes.dropdowns.for.dom.jan.3rd.2020.xlsx)

**Comment by dominijk** [comment]
File is now stored [here](https://liveuclac-my.sharepoint.com/:x:/g/personal/ucfndhu_ucl_ac_uk/Ebiflo4qQoJJhKUicJ7DwY8BxbXosOpbQXJkSdMV2BLyfQ?e=abczf3) please only edit into this file, access is linked to your email
