### ISSUE TITLE
Bulk upload victorian data, computational generation testing

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#582]
@dominijk @mz8i First computational age data generation working with Flora at Turing.  CL Age data categories as follows

Year built: 1890
Latest start: 1898
Earliest start:1880
Facade: 1890
Source of info = Computational generation (NB new source category required)
Source details = Turing Institute (Roumpani/Hudson/Stanilov)
Link

Ideally need verification on this one asap

**Comment by dominijk** [comment]
@polly64  I have two questions on this, one of which might be answered when we have the data. The other will still be relevant

- What is the identifier we will use to bring the data in (a coordinate or UPRN) 
- Can you confirm that you want us to bring all this data in as is. Ie it will replace any data that others have already entered into the database 
- Who will the upload user be? Same as phd data? `ph_ucl_2016` 

From the CL side this needs the following work
- Update database design to add new source category and source
- Verification feature (longer term development item)

**Comment by polly64** [comment]
@dominijk 
1. Identifier is TOID ID as attached in email
2. Yes bring all data in Flora has removed everything within my Camden sample area and most is on inner London border and shouldn't overlap with current additions
3. Uploader is 'Alan Turing Institute. Computational generation test'.

**Comment by polly64** [comment]
Date Built - 1890
Earliest possible 1880
Latest possible 1899
Facade date - 1890
Source dropdown - computational generation (needs to be added)
Source  'Alan Turing Institute. Computational generation test'
No link yet
