### ISSUE TITLE
Materials API upload

### ISSUE THREAD

**Issue by dominijk** [colouring-london/colouring-london#594]
Could related to #593 

With bulk upload through API when posting to `construction_core_material` and `roof_covering` only edits to `construction_core_material` are saved to db. On second post using same data `roof_covering` saves

**Comment by polly64** [comment]
@dom @ melda - dom many thanks  for loading brick 1880-1899 in. I see  quite a lot aren't loading still (gaps in middle of terraces -easy to manually fill you can easily see where i did yesterday -@ tom what's best plan do u think going forward do you think to help fill terraces in completely in each time we upload ?
