### ISSUE TITLE
Current Use legend colours mismatch

### ISSUE THREAD

**Issue by mz8i** [colouring-london/colouring-london#600]
Colour for Transport is different between map and legend. Potentially, there are other mismatches, too (but haven't verified that).
See on the example of Cannon St Station:
![image](https://user-images.githubusercontent.com/36160844/84399484-d27f0400-abf8-11ea-9390-94411e8587c2.png)

**Comment by polly64** [comment]
yes have raised with Tom but let's talk Thurs
