### ISSUE TITLE
Issues with my account: I.E mistakingly blocked

### ISSUE THREAD

**Issue by KayaanM** [colouring-london/colouring-london#611]
From October 2019 when I first signed up to colouring london, I had been contributing to London’s architectural history. Myself and other contributors have noticed that some of our data has been and deleted or wiped out either by error or by a another person.
This has been a problem for me for quite a while as I have been mistakingly or intentionally locked out of the account which means that I am disabled from continuing.
I have read previous complaints from others and would like to see this issue resolved where I can access my account and still see the info and edits I have made.

**Comment by polly64** [comment]
We thank you very much for your contribution and apologise if any of  your contributions have been deleted. We are currently uploading 240,000 interwar entries which have been  automatically generated  from historical maps and we are in the process in the following days of going through to check whether any contributions have been overwritten , and to reinstate them if this has occurred.  

 We noticed a problem with random deletions occurring some months ago and put some measures in to prevent these happening.  These have obviously not been sufficient. Editors are permitted to alter entries and these can be seen in the edit history but no entry should be able to deleted without it being replaced by another.  We will be looking at this as a priority issue over the next week to ensuring yours and other entries are reinstated. We will provide further feedback on this issue in the following days in this location.   We thank you again for your contributions  and look forward to resolving the issue as quickly as possible.

**Comment by tomalrussell** [comment]
Good morning @KayaanM - thanks for letting us know and creating this issue, the feedback is super important :heart: :pray: 

Even with the issues you've been facing, as far as I can see, you're one of the top ten contributors to the site, with over 4000 edits. Thanks again, I hope we can get you up and running soon.

**Comment by polly64** [comment]
Have attached screenshot from our top 10 contributor leaderboard (from our new menu,) thank you again!
![Kayaan on top ten entries on leaderboard](https://user-images.githubusercontent.com/42236514/84998832-41ec7a80-b148-11ea-84bd-6b7f69dc4995.JPG)

**Comment by polly64** [comment]
Hi @KayaanM your account is active again.  It appears that your previous account appeared - as well as showing many  new entries - to be automatically deleting existing entries or entering values of '1'  which is why it had to be  temporarily suspended.  It think  you may not have received an email about this that we sent at the time. We  think we have now  resolved the issue of deletion occurring. If you have any further problems please so not hesitate to contact us on this thread. Thank you very much again for your valuable date contributions.

**Comment by tomalrussell** [comment]
Hi @KayaanM - can you confirm that you can log in and use the site okay now?

**Comment by KayaanM** [comment]
Hello,
I have been able to log in successfully to Colouring in London, thank you.

Kind Regards
Kayaan.

**Comment by tomalrussell** [comment]
Fantastic - thanks for getting in touch. Feel free to open more issues here if you have ideas, problems or questions.

All the best,
Tom

**Comment by polly64** [comment]
@KayaanM  great, and thanks again for all past entries and anything you may be able to add going forward
