### ISSUE TITLE
Pure black "night" style

### ISSUE THREAD

**Issue by tomalrussell** [colouring-london/colouring-london#615]
**Describe the solution**
Update the "night" style maps to use a pure black background, dropping the OS basemap.

**Describe any alternatives**
Custom, darker dark styles based on OS data and Mapnik styles, or customisation of OS Zoomstack with a vector tiles approach - either may be worth exploring more in future.

**Additional context**
Designing colour schemes against the dark blue/green OS "night" basemap is somewhat limiting, worth testing against a pure black. 

@polly64 finds the "light" background generally easier to work with while editing; the "night" background is fun to switch over to look at the data as more artistic visualisation.

**Comment by polly64** [comment]
@tom this would keep streetnames wouldn't it?

**Comment by tomalrussell** [comment]
This would drop streetnames on the "night" view, and keep them on the "light" view.

**Comment by polly64** [comment]
@tomalrussell i think we might need to look at another option as i think we need streetnames on this one too.  I know @mz8i also raised  issue of needing to address issue of  text sometimes  being under buildings so maybe we should talk about this and streetname issue together
