### ISSUE TITLE
Add Colouring Cities logo on landing page

### ISSUE THREAD

**Issue by mz8i** [colouring-london/colouring-london#636]
Requirement from #618 : Let's try it next to the Colouring London Logo ( make this slightly smaller than it is now and leave slight gap between them so they can be read separately

**Comment by mz8i** [comment]
@polly64 if you mean putting it in the header next to where the current logo is, it could look a bit strange if we had to hide/show it depending on the page you're on, meanwhile keeping it visible all the time will make the interface a bit cluttered on the view/edit pages...

Could we try another layout first? 
Perhaps we could put the CC logo in one row with the ATI logo (#637), below the 'Start Colouring' button and above the other institution logos?

**Comment by polly64** [comment]
@mz8i yes, let's try that for now
