### ISSUE TITLE
Update landing page text

### ISSUE THREAD

**Issue by mz8i** [colouring-london/colouring-london#638]
Keeping existing links on 'open code' (to github) and 'open licence' terms (to licence page):

'Welcome to Colouring London!
Colouring London is a free, knowledge exchange platform designed to provide over fifty types of open data on London buildings, to help make the city more sustainable.

Colouring London is also the prototype for the Colouring Cities Research programme based at the Alan Turing Institute (the UK's national Institute for data science and artificial intelligence). The programme works with local, regional, national and international partners to develop open platform code also of relevance to other cities. New datasets and features are added all the time. Any help you can give, colouring-in our building maps, and enriching and verifying our open datasets is very much appreciated. All our data, maps and code are free to downloaded, use and share under our open licence terms'.

**Comment by mz8i** [comment]
@polly64 is it OK that there will be no mention/link to the data ethics policy if we replace the current welcome text with the proposed one?

**Comment by polly64** [comment]
@mz8i yes because it is on menu and it is also required to be read on sign up i believe (could u double check?)

**Comment by mz8i** [comment]
@polly64 that's right, the data ethics policy is available elsewhere.

On a separate note, I am not sure which document we should link to as the 'license'
The options I identified are:
- the contributor agreement
- data accuracy agreement
- soure code licence (GPL) in the GitHub repository

**Comment by mz8i** [comment]
@polly64 actually, just an additional note - the data ethics page is linked to from the menu, but not from the sign up page

**Comment by polly64** [comment]
@mz8i can we say on sign up page  'Please also see our data ethics page' and give link?

**Comment by polly64** [comment]
@mz8i  I have omitted the word ' maps' from last line in the above text.  Could you link the word 'data' in this line to the contributor agreement and 'code' to the source code licence

**Comment by mz8i** [comment]
Added the data ethics note on sign up. I actually left the data/code links to point to the downloads page and GitHub, respectively, as they then point to the licences/agreements themselves.
The mention of 'open licence' at the very end doesn't have a link as I still wasn't sure what to link to, but we can add it later. Or could reword / cut off that final bit?
