### ISSUE TITLE
Correct category sidebar grid formatting

### ISSUE THREAD

**Issue by mz8i** [colouring-london/colouring-london#643]
From #618 : "Correct category 12 grid as reading 3x 4 rather than 4 x 3 when in edit mode"

**Comment by mz8i** [comment]
@polly64 could you please clarify the following:

- the desired outcome is always 3 rows x 4 columns like in the logo, correct?

- when / where can you encounter the undesirable layout? Specifically, what browser and what kind of device / screen size?

- also, could you please check that you don't have a custom zoom level set in the browser? (you can usually reset it by pressing Ctrl+0 on a PC)

Testing locally, I've been able to see that the layout changes but only on narrower screens like a mobile phone, where it might be difficult to prevent this without making the text in the category squares very small

**Comment by polly64** [comment]
@mz8i 
1) yes desired outcome like logo

2) on my mac . On firefox and internet explorer. my computer size is 15 inch macbook pro

3) same happens on different browsers - on mac using windows

4) that's good if not happening on others
