### ISSUE TITLE
measuring outputs

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#65]
I put in grant  we would provide following outputs could u check mechanisms in place to record.  I will a dd survey monkey questionnaire
1)  in sign in data can we have place to which to link to anonymous survey which will ask whch sector you're from, gender (as we'r looking for 50/50 split - OSM is 3-5% women editors according to surveys, wikipedia about 16%.  So looking to produce graphs showing
2) no of website hits per month
3) No of sign ups per month
4. Total no of entries per month by category
5. Total no. of edits per month by category
6. No. of downloads (when operational)

**Comment by dominijk** [comment]
@polly64 Will this be voluntary but nudged toward providing or compulsory (you can't sign up without providing this)

**Comment by dominijk** [comment]
Realtes to #62
