### ISSUE TITLE
Check and Update all category and subcat titles & include greyed out

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#663]
@mz8i we need to do a clean through of all the category titles - also as a priority so CC partners know what's coming. These are the revisions, hopefully they will be quite quick

LOCATION

- [ ] Add 'Open TOID' box next to UPRN box (greyed out for moment
- [ ] Rename 'UPRNs' to ' 'Open UPRN'

CURRENT USE - No change

TYPE

- [x] Add/order the following subcategories, in following order :
- [x] 'Base type classification' (add greyed out)
- [x] 'Local typology classification' (add greyed out)
- [x] 'Original land use' (use existing)
- [x] 'Roof type' (Move this from 'SIZE & SHAPE')
- [x] 'Adjacency/Configuration' (keep existing but adjust name)
- [x] 'Local typology mutations' (add greyed out)
- [x] '3D Procedural model classifications' (add greyed out)
- [x] 'Dynamic tissue type classification' (add greyed out)

AGE - No Change

SIZE & SHAPE
- [x] Change main category title to ' SIZE' not 'Size & SHAPE'
- [x] Add 'Total opening area' (greyed out for moment) at end of list
- [x] Move 'Total area of plot' and ' FAR ratio' to 'STREETSCAPE' as below
- [x] Move 'roof shape' to 'TYPE' as above
- [x] Delete 'configuration' as already in 'TYPE'

CONSTRUCTION
- [x] Add ' Construction system' below other subcats (greyed out/non operational)

STREETSCAPE
- [x] Change the text in blue box to say 'This is what we're planning to collect on the building's context'
- [x] Delete 'What's the building's context? Coming soon
- [x] Move the following from 'SIZE & SHAPE'
'Total area of plot' 
'FAR ratio' 
- [x]  Add the following below these subcats- can be just as greyed out list for moment
'Plot dimensions'
'Plot geometry link' 
'Land ownership parcel link'
'Land ownership type'
'Street width'
'Street network geometry link'

TEAM
- [x] Change the text in blue box to say 'This is what we're planning to collect in this section'
- [x] Add to existing list
'Awards'

PLANNING - No change

SUSTAINABILITY
- [x]  Add the following two categories greyed out/non operational
' Repairability rating for type'
'Adaptability within plot rating'

DYNAMICS

- [x] Add the new section on 'Historical constructions and demolitions'
- [x] Delete all items on current list
- [x] Add following subsection titles greyed out below 'Historical constructions and demolitions'
'Historical land us change'
'Longitudinal historical footprints (raster) link'
'Longitudinal historical footprints (vector) link'
 

'

**Comment by polly64** [comment]
@mz8i    sorry can you make the 'Local typology classification' say ' Local typology/architectural style' instead

**Comment by mz8i** [comment]
@polly64 this is now released. A couple of notes:

- as discussed, I didn't change the TOID/UPRN labels. After we import the lat/lon data from the Open TOID dataset, it might be best to add a notice next to the coordinate fields
- one leftover field in Type is "When did use change?" - what do we do with it?
- re "Type" category - it's always felt to me that just judging from the name, it's difficult to tell what info the category encompasses... Would there be any other name that would be more informative? Sth like "Form" maybe?
- for Size, the WIX pages link is https://pages.colouring.london/shapeandsize - let me know if you'll want to rename the category on that page, too, so that I can later update the URL
- I have made the changes to dynamics, although will add the new interface in a separate batch of changes, so for now the section on constructions/demolitions has simple placeholder fields (current/past buildings)

**Comment by polly64** [comment]
@polly64<https://github.com/polly64> this is now released. A couple of notes:

  *   as discussed, I didn't change the TOID/UPRN labels. After we import the lat/lon data from the Open TOID dataset, it might be best to add a notice next to the coordinate fields
Yes
  *   one leftover field in Type is "When did use change?" - what do we do with it?
Omit we need to think about this
  *   re "Type" category - it's always felt to me that just judging from the name, it's difficult to tell what info the category encompasses... Would there be any other name that would be more informative? Sth like "Form" maybe?
let's chat
  *   for Size, the WIX pages link is https://pages.colouring.london/shapeandsize<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpages.colouring.london%2Fshapeandsize&data=04%7C01%7C%7C306c94a8e57a4a72654408d8d93fa671%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C637498214693899225%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ASlkwEne8Bz3pYRkQvAXlVjg0%2FJWfTl%2BYuCjTdcL7JE%3D&reserved=0> - let me know if you'll want to rename the category on that page, too, so that I can later update the URL
Yes please
  *   I have made the changes to dynamics, although will add the new interface in a separate batch of changes, so for now the section on constructions/demolitions has simple placeholder fields (current/past buildings)
great

**Comment by mz8i** [comment]
It's worth noting that the "When did use change?" field has been active and there is data added in this field for 16 buildings in the live system. I would not delete the data, only remove the field from the interface, but it's something to be mindful of.

Also, another question: after the changes, Streetscape has a mix of bullet points on data we'd like to collect, and deactivated fields. Is this correct or should I remove the bullet points? Can you have a look at live site please?

**Comment by polly64** [comment]
ok will think about first point when we talk.  second point can you move this list 'green list to the bottom


Polly Hudson

Senior Research Fellow Bartlett Centre for Advanced Spatial Analysis

University College London

90 Tottenham Court Road W1T 4TJ


Research Fellow, The Alan Turing Institute

Director - Colouring London https://colouringlondon.org/


No response to this email is presumed outside standard working hours.



________________________________
