### ISSUE TITLE
'Tenure' subcategory  discussion points

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#68]
We could include 'tenure' under land use as keeps coming up in consultations particularly with local authorities.
Need to talk further about this but here are some discussion points
The main one is how can we collect tenure data so that we don't invade privacy? Our other categories deal with the exterior of building, or historical info- ie even number of SCU's can be identified just by number of bells.  I think we can get round this by having 3 very simple categories which relate only to land ownership not leasehold

( ' Use'- this is our next category to be uploaded ) so suggesting
Category title= Land Use
Subcategories =NLUD  Order, NLUD group, NLUD Class, How many Seldf contained units- SCUs (UCl energy definition) , Tenure
Tenure dropdown = 
Is it 
single type tenure OR mixed tenure types
then in each of these can select and if necessary combine

local authority owned
non profit making independent organisation owned
privately owned individual/s
privately owned company

**Comment by dominijk** [comment]
Picking up notes from discussion with @polly64 for **Ownership** menu as below, after;

Email Guy Shrubsole for categories 

Default is to colour all buildings as private ownership, we won't collect data on who the owner is this is already recorded by [whoownsenlgand](https://whoownsengland.org/). Possible source for some bulk uploads as is the OS Vectormap local (important buildings) 

Add caveat that we aren't showing freehold extent and only legal source for this data is land registry. 

Freehold ownership |  
-- | --
Categories | Private, State, Thirdsector, ? Institutions
