### ISSUE TITLE
UPDATED CONTRIBUTOR AGREEMENT' AND 'DATA ACCURACY' to improve clarity and transparency

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#689]
@tomalrussell @mz8i @matkoniecz @Ismael-KG (Turing Ethics) I have rewritten these to improve clarity and transparency - if you could read and make any comments that would be great

DATA ACCURACY AGREEMENT
Colouring London data are provided "as is", without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, accuracy, fitness for a particular purpose and non-infringement. In no event shall the Alan Turing Institute be liable for any reliance that you place on or how you use the data nor any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the data or the use or other dealings in the data.

Colouring London data are crowdsourced from multiple sources and may contain errors. Though we cannot comment on data accuracy, we try to include as many features as possible to help users assess their reliability and suitability for specific types of use (be this a school project or scientific paper). As information on sources is very important, contributors are asked to add these, and to verify data, wherever possible.

CONTRIBUTOR CODE OF CONDUCT

This Code of Conduct is adapted from the Contributor Covenant, version 1.4, available at https://www.contributor-covenant.org/version/1/4/code-of-conduct.html.

**Our Pledge**
In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to make participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

**Our Standards**

- Examples of behaviour that contributes to creating a positive environment include:
- Using welcoming and inclusive language
- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Focusing on what is best for the community
- Showing empathy towards other community members
- Examples of unacceptable behaviour by participants include:
- The use of sexualized language or imagery and unwelcome sexual attention or
- advances
- Trolling, insulting/derogatory comments, and personal or political attacks
- Public or private harassment
- Publishing others' private information, such as a physical or electronic address, without explicit permission
- Other conduct which could reasonably be considered inappropriate in a professional setting.

**Our Responsibilities**
Project maintainers are responsible for clarifying the standards of acceptable behaviour and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behaviour.
Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviours that they deem inappropriate, threatening, offensive, or harmful.

**Scope**
This Code of Conduct applies within all project spaces, and it also applies when an individual is representing the project or its community in public spaces. Examples of representing a project or community include using an official project e-mail address, posting via an official social media account, or acting as an appointed representative at an online or offline event. Representation of a project may be further defined and clarified by project maintainers.
Enforcement
Instances of abusive, harassing, or otherwise unacceptable behaviour may be reported by contactingteam@colouring.london or dataprotection@turing.ac.uk. All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality with regard to the reporter of an incident. Further details of specific enforcement policies may be posted separately.
Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project's leadership.

For answers to common questions about this code of conduct, see https://www.contributor-covenant.org/faq.

**CONTRIBUTOR AGREEMENT**

**Contributor responsibilities**
We ask all our contributors to:
•	adhere to our Code of Conduct
•	never knowingly add data that derives from a restricted, copyrighted. malicious or illegal source
•	help us create an open data platform that supports the development of sustainable, resilient, inclusive, and equitable cities, and encourages the use of data for the public good
•	add sources wherever possible, to benefit others
•	verify data, whenever possible, to benefit others
•	ensure our open licencing terms are fully adhered to with regard to our open data, and our open code
•	provide us with as little personal data as possible
•	take full responsibility for assessing the reliability of Colouring London data and its suitability for any intended use (see also our 'Data Accuracy Agreement')
•	provide feedback on actual or potential privacy and security concerns.

**Additional notes for contributors**

**Open data**
Colouring London is an open data project. Open data are licensed under the Open Data Commons Open Database License (https://opendatacommons.org/licenses/odbl/) by Colouring London contributors. Under this licence you are free to copy, distribute, transmit and adapt our data, as long as you credit Colouring London and our contributors. If you alter or build upon our data, you may distribute the result only under the same licence. Our open platform code are available under a GNU, General Public Licence (https://www.gnu.org/licenses/gpl-3.0.en.html).

**What you are contributing to**
'Colouring London is a free knowledge exchange platform and open database designed for public use. It has been set up to support a whole-of-society approach to improving the sustainability, resilience and inclusivity of cities. Colouring London is also the prototype platform for the international Colouring Cities Research Programme (CCRP) run at the Alan Turing Institute. Its design is guided by principles set out in the United Nations New Urban Agenda, the Open Data Charter, the General Data Protection Regulation (GDPR), The Gemini Principles, the Open Data Institute's recommendations on personal data and data infrastructure, and specific Articles within the Declaration of Human rights. These are discussed on our 'Data ethics' page (https://github.com/colouring-london/colouring-london/issues/), where we also use the Open Data Institute's data ethics canvas to answer questions on how we use and manage our data. We capture spatial statistics and do not collect text or images, though images may be integrated in the future. The type of spatial data we collect can be viewed by clicking on each data category, on 'Info' buttons and on the 'Building data categories' page. We are also planning a 'Showcase section' to enable platform users to share, and view, ways in which Colouring London data are used.

**Diversity and inclusivity**
We are very grateful for all constructive contributions provided by our contributors. Our platform is designed for everyone, and we are working to make it as inclusive, welcoming and accessible as possible. We respect and actively seek diversity of contributors and audiences, and celebrate diversity of knowledge. We use colour, crowdsourcing, and non-technical language to reduce barriers to the contribution of statistical information and to make the process rewarding and interesting. Diversity of age, gender, skills and abilities, and cultural background is also essential to allow us, as communities, to make our cities and towns more inclusive, equitable, sustainable and resilient places. Our collective knowledge on the composition, dynamic behaviour and energy performance of our stocks, and how well our buildings work, is critical to inform policies on what buildings we should reuse, demolish and build anew, to accelerate retrofit, and to better understand stocks as dynamic systems, so that they may be improved.

**Copyright and data accuracy and quality**
We are unable to accept any data derived from copyrighted or restricted sources, other than those covered by fair use, nor from illegal sources, and we ask contributors to carefully check sources prior to upload. We are also unable to take responsibility for the quality of datasets as it is not feasible to check each data entry, and as different degrees of accuracy and precision will be required by different users, depending on what they are using the data for (e.g. a school project or scientific paper). However our aim is to make our data as reliable and useful as possible. We therefore ask contributors to include sources and to verify other data entries wherever possible. 
For information on data privacy and security please see our Privacy and Security page

**PRIVACY POLICY & PLATFORM SECURITY**

**Colouring London Privacy Policy with respect to personal data**

This privacy policy explains how Colouring London uses the personal data we collect from you when you use our website. Colouring London is a research project initially developed by the Bartlett Centre for Advanced Spatial Analysis (CASA) at UCL, and now run at The Alan Turing Institute. Colouring London is registered for data protection purposes with The Alan Turing Institute data protection office.

**What data do we collect?**
Colouring London collects the following personal data:
A username and email address. We recommend you do not use your actual name for your username. We also collect your password, which is stored as a cryptographic hash unique to Colouring London.

**How do we collect your data?**
You provide Colouring London with a minimal amount of personal data when you register with the website and accepts the terms and conditions including this privacy policy.

**What purposes do we use your data?**
Colouring London uses your personal data to enable you to login to access and contribute to the Colouring London project and to provide a personalised user experience when you are logged in. We will not share your personal data (such as your email address) with any other parties or use your personal data for any purposes other than the Colouring London project. If you request a password reset, an automated email will be sent using Mailgun, who process the email in order to deliver it to your email address. Mailgun retain personal data they process on behalf of Colouring London for as long as is needed to provide email services. Mailgun will retain the personal information as necessary to comply with their legal obligations, resolve disputes, and enforce their agreements.

**What is the legal basis for processing your data?**
Data protection laws require us to meet certain conditions before we are allowed to use your data in the manner described in this notice, including having a ‘legal basis’ for the processing. Colouring London, as a research project, is processing your personal data in pursuance of its legitimate interests.

**How do we store your data?**
Colouring London stores your data at The Alan Turing Institute in London behind the organisation’s firewall in a secure database using industry standard practices.

**How do we use cookies?**
Colouring London only uses cookies to improve the user experience of users of the website, for example we use cookies to keep you signed in. We do not use cookies for marketing or advertising purposes.
What are your data protection rights?
Under the General Data Protection Regulation, you have certain individual rights in relation to the personal information we hold about you. For the purposes of research where such individual rights would seriously impair research outcomes, such rights are limited. However, subject to certain conditions, you have the following rights in relation to your personal data:
• A right to access personal data held by us about you.
• A right to require us to rectify any inaccurate personal data held by us about you.
• A right to require us to erase personal data held by us about you. This right will only apply where, for example, we no longer need to use the personal data to achieve the purpose we collected it for.
• A right to restrict our processing of personal data held by us about you. This right will only apply where, for example, you dispute the accuracy of the personal data held by us; or where you would have the right to require us to erase the personal data but would prefer that our processing is restricted instead; or where we no longer need to use the personal data to achieve the purpose we collected it for, but we require the data for the purposes of dealing with legal claims.
• A right to receive personal data, which you have provided to us, in a structured, commonly used and machine-readable format. You also have the right to require us to transfer this personal data to another organisation.
• A right to object to our processing of personal data held by us about you.
• A right to withdraw your consent, where we are relying on it to use your personal data.
• A right to ask us not to use information about you in a way that allows computers to make decisions about you and ask us to stop.

It is important to understand that the extent to which these rights apply to research will vary and that in some circumstances your rights may be restricted. If you notify us (using the contact details set out below) that you wish to exercise any of the
above rights and it is considered necessary to refuse to comply with any of your individual rights, you will be informed of the decision within one month and you also have the right to complain about our decision to the Information Commissioner’s Office.

Please also note that we can only comply with a request to exercise your rights during the period for which we hold personal information about you. If that information has been irreversibly anonymised and has become part of the research data set, it will no longer be possible for us to access your personal information.

**Changes to this privacy policy**
Changes to this privacy policy will be notified via the Colouring London website. This privacy policy was last updated on 4th November 2021. Previous update 2nd October 2021 following change ownership from UCL to The Alan Turing Institute. 

**Who do I contact with questions?**
If you wish to complain about our use of your personal data or exercise any of your rights, please contact the Turing's Data Protection Officer: dataprotection@turing.ac.uk or Data Protection Officer, The Alan Turing Institute, 96 Euston Road, London NW1 2DB.

If we are unable to adequately address any concerns you may have about the way in which we use your data, you have the right to lodge a formal complaint with the UK Information Commissioner's Office. Full details may be accessed on the complaints section of the Information Commissioner's Office website.

**Further information on privacy and security**
Please note when you make a contribution to Colouring London, you are creating a permanent, public record of all data added, removed, or changed by you. The database records the username and ID of the user making the edit, along with the time and date of the change. All of this information is also made publicly available through the website and through bulk downloads of the edit history. User names of contributors providing the highest number of edits are also included in our 
Leaderboards.

Please also note that when you contribute to Colouring London, you make your contributions available as open data for anyone to copy, distribute, transmit and adapt in line with the licence, and to use as they see fit. Though we rigorously assess each data type, to help protect building occupiers' privacy and security we welcome any ideas for improvements. 

Progress on Colouring London features specifically designed to address ethical issues, including these relating to security and privacy, can be tracked and commented on using our GitHub site, at https://github.com/colouring-london/colouring-london/issues/687. If you have any immediate concerns regarding security or privacy please contact Turing's data protection team at dataprotection@turing.ac.uk.

**Comment by matkoniecz** [comment]
> Though we cannot comment on the accuracy of data

maybe

> Though we cannot guarantee accuracy of data

would be better?

**Comment by polly64** [comment]
@matkoniecz @tomalrussell thanks, have changed above, and also have removed the ref to  teams@..under 'scope' and replaced with turing data protection email for now.  Could you both talk further re email address thanks, and @matkoniecz if you can also contact Turing departments in WT's email so see if they have any thoughts that would be great.

**Comment by polly64** [comment]
@tomalrussell @matkoniecz thanks for email Tom. I have added back team@ but also kep the turing data protection as well as a back up.  @matkoniecz this is now ready to upload

**Comment by matkoniecz** [comment]
@polly64 

It was my initial deployment, so nearly entire time was spend with Maciej on discussing technical setup. There is also ongoing work to document it better so in future it will be easier to access this info (especially if he and/or me would be unavailable or forgot something).

https://colouringlondon.org/data-accuracy.html is deployed (with provided version, should I also include https://github.com/colouring-london/colouring-london/issues/689#issuecomment-961711210 ? )

https://colouringlondon.org/code-of-conduct.html is deployed

remaining ones will be deployed after I document what I learned about structure, deployment process and some technical solutions

**Comment by polly64** [comment]
@matkoniecz thanks, let's talk re whether we include the issue 689 link next time we speak

**Comment by matkoniecz** [comment]
@polly64 

> This privacy policy was last updated on 4th November 2021. Previous update 2nd October 2021 following change ownership from UCL to The Alan Turing Institute.

there seems to be a typo here, see https://github.com/colouring-london/colouring-london/commits/master/app/src/frontend/pages/privacy-policy.tsx

Previous update appears to be in 2019, with two later being a technical changes not affecting page text. I will put 2019 on the published page, resulting in

> This privacy policy was last updated on 4th November 2021. Previous update 2nd October 2019 following change ownership from UCL to The Alan Turing Institute.

(I can also change "last updated on" to actual deployment date)

**Comment by polly64** [comment]
@matkoniecz  yes thanks for spotting

**Comment by matkoniecz** [comment]
@polly64 

I will also change

> These are discussed on our 'Data ethics' page (https://github.com/colouring-london/colouring-london/issues/), where we also use 

to

> These are discussed on our <a href="https://github.com/colouring-london/colouring-london/issues/687">'Data ethics'</a> page

as it seems to be preferred formatting - let me know if original was intentional.

I also think that linking something specific in "provide feedback on actual or potential privacy and security concerns" could be useful. For example "provide feedback" can link https://github.com/colouring-london/colouring-london/issues or https://github.com/colouring-london/colouring-london/issues/687

**Comment by polly64** [comment]
Yes great. In Cambridge today so prob won’t pick up emails Until and can’t make meeting with u and Tom Friday but we could do Friday pm for a half hour catch up if you’re free? Or the following week justs let me know what’s good





Polly Hudson

Senior Research Fellow, Bartlett Centre for Advanced Spatial Analysis, UCL.


Senior Research Fellow, The Alan Turing Institute

Project Lead, Colouring Cities Research Programme
https://www.turing.ac.uk/research/research-projects/colouring-london-and-colouring-cities-research-programme





No response to this email is presumed outside standard working hours.



________________________________

**Comment by matkoniecz** [comment]
> Privacy Policy & Platform Security

should it be also renamed in sidebar?

![screen03](https://user-images.githubusercontent.com/899988/140787729-641d3987-376a-41d8-8359-502d86ef82b8.png)

**Comment by matkoniecz** [comment]
> Privacy Policy & Platform Security

should it be also renamed in sidebar?

![screen03](https://user-images.githubusercontent.com/899988/140788549-f4e1d782-2931-4ef7-b494-04c7d5eac737.png)

**Comment by matkoniecz** [comment]
Fully deployed, though some tweaks (mentioned above) may still need to be handled.
