### ISSUE TITLE
unable to zoom close/zoomed out

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#695]
Hi @matkoniecz on chrome the landing page text has shrunk and feels as if i'm zoomed out- also  I'm unable to zoom in as close to buildings ( we can on staging) , and can't read street names. On firefox it's fine could you possibly have a quick check on this? thanks

**Comment by matkoniecz** [comment]
Hm, from quick check everything seems fine to me (on specific browser-OS etc combination).

Can you open Chrome and press `ctrl` and `0` buttons at the same time?

Or in other way reset zoom level to default?

It is possible that some of ways to activate zooming out was activated, and this is remembered by browser for each domain separately, what would explain why staging is not affected.

**Comment by polly64** [comment]
@matkoniecz  brilliant works!
