### ISSUE TITLE
Zoom in closer so more colour coverage -user motivation 

### ISSUE THREAD

**Issue by polly64** [colouring-london/colouring-london#72]
Sorry if a response you gave before came via email (will try to find) but also creating this issue as place  give us an  area to talk about zoom level and user motivation.  Testing with teenage users  yesterday they were really excited by colour changing (which was great) and would have added info to other buildings  (again great) but scale of task felt daunting because of number of buildings on the screen. I realised much more powerful reward mechanism if colour is fills screen as much as possible, so ideally wanting to increase zoom level to where only say 4 buildings visible.  This  helps drive motivation to move to next one.

**Comment by polly64** [comment]
Just to add I think we're probably ok to go at moment but worth chatting about this and perhaps posing as a question

**Comment by polly64** [comment]
actually think we need to try and zoom in more - is this an OS restriction issue?

**Comment by tomalrussell** [comment]
This is more of a technical restriction - we use the OS basemap for the night/light styles, which only go to zoom level 18 (which is the max we have).

Rendering a basemap for the higher zoom levels ourselves should be possible but requires a chunk of work.

Notes:
- https://www.ordnancesurvey.co.uk/blog/2017/12/effective-basemaps/
- https://github.com/OrdnanceSurvey/GeoDataViz-Toolkit/tree/master/Basemaps
- https://www.ordnancesurvey.co.uk/resources/carto-design/cartographic-stylesheets.html
- https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets
- https://github.com/springmeyer/geotools2mapnik

**Comment by tomalrussell** [comment]
May help with #54 #53 #11

**Comment by tomalrussell** [comment]
Yes - relevant notes for mobile design (size guidelines for things to click): https://www.lukew.com/ff/entry.asp?1085

**Comment by tomalrussell** [comment]
Considering this closed by #466
